#pragma once
#include "Game/GameCommon.hpp"

enum class ChessMoveResult
{
	UNKNOWN = -1,

	VALID_MOVE_NORMAL,
	VALID_MOVE_PROMOTION,
	VALID_CASTLE_KINGSIDE,
	VALID_CASTLE_QUEENSIDE,
	VALID_CAPTURE_NORMAL,
	VALID_CAPTURE_ENPASSANT,

	INVALID_GAME_NOT_PLAYING,
	INVALID_MOVE_BAD_LOCATION,
	INVALID_MOVE_NO_PIECE,
	INVALID_MOVE_NOT_YOUR_PIECE,
	INVALID_MOVE_ZERO_DISTANCE,
	INVALID_MOVE_WRONG_MOVE_SHAPE,
	INVALID_MOVE_DESTINATION_BLOCKED,
	INVALID_MOVE_PATH_BLOCKED,
	INVALID_MOVE_ENDS_IN_CHECK,
	INVALID_MOVE_PAWN_WRONG_PROMOTION,
	INVALID_ENPASSANT_STALE,
	INVALID_CASTLE_KING_HAS_MOVED,
	INVALID_CASTLE_ROOK_HAS_MOVED,
	INVALID_CASTLE_PATH_BLOCKED,
	INVALID_CASTLE_THROUGH_CHECK,
	INVALID_CASTLE_OUT_OF_CHECK,

};

bool IsValid(ChessMoveResult result);
const char* GetMoveResultString(ChessMoveResult result);
